### ISSUE TITLE
Links link to arch packages/wiki instead of a universal source.

### ISSUE THREAD

**Issue by onodera-punpun** [TheReverend403/rice-stuff#18]
Like 70% of the links on this website/readme link to either the arch packages or the arch wiki instead of the real source or website.

Not everyone uses arch, the wiki thing is still acceptable, but linking to the arch repo/aur is really not in my opinion.

If you /want/ to link to some kind of third party website use the lfs website, since they explain how to build the package, what the decencies are and what they do, and what patches to apply.

**Comment by TheReverend403** [comment]
I only count 3 links to Arch packages, and as far as I can tell, those packages aren't really available elsewhere in any sort of unified format.

**Comment by onodera-punpun** [comment]
Sorry, you are right, I quickly skimmed over all the links and saw lots of arch.

What do you think about adding multiple links to each program, for example: wayland - *website* *arch-wiki* *gentoo-wiki* *lfs*?

**Comment by TheReverend403** [comment]
I feel like that'd get very messy, very quickly.

**Comment by skewerr** [comment]
I did do a similar thing for the MacType installer because it went offline, maybe it can be done for some links when strictly necessary. Pick a link to be displayed and put the others to the side of it.

**Comment by neeasade** [comment]
maybe 
program-name [1] [2] [3]

with 1, 2, 3 being the links to different sources?

**Comment by skewerr** [comment]
That could work, but I'd rather have the name of the sources.

**Comment by neeasade** [comment]
> Will they use the same icon?  

That's what I had in mind - I guess my fear is that if will be messy as @TheReverend403 indicated, and I see icons as less messy. But I do see the loss of clarity there opposed to abbreviated text or something. mehr.

**Comment by TheReverend403** [comment]
It's not just about being messy, we have to consider contributors. the more things we add, the higher the barrier of entry for contributors, because they have to learn more and more of the style conventions and what everything means.

**Comment by neeasade** [comment]
That is a good point.
