### ISSUE TITLE
You should merge the master branch into gh-pages to make changes available

### ISSUE THREAD

**Issue by tudurom** [TheReverend403/rice-stuff#32]
Also, please add http://gratisography.com/ to the list of wallpaper sites.

**Comment by neeasade** [comment]
? the gh-pages branch is regenerated everytime a commit occurs on the master branch.

**Comment by tudurom** [comment]
#31 got merged and the changes are not visible.

**Comment by neeasade** [comment]
welp 

paging @TheReverend403

**Comment by TheReverend403** [comment]
Fixed in 0d0775823829ca9f62f65ffb64502a54830f0eca
