### ISSUE TITLE
Enhancement: anchor tags on headers

### ISSUE THREAD

**Issue by neeasade** [TheReverend403/rice-stuff#5]
I would like to be able to click next to a header to get an anchor tag to that header, or just be able to anchor link to a header. For example here, I would love to be able to header link to the colors section:

https://www.reddit.com/r/unixporn/comments/3l3y7r/readable_terminalshell_themes/

**Comment by neeasade** [comment]
Not quite - 

for example http://ref.ochazuke.org/#bars doesn't scroll to bars header, still loads page at top.

**Comment by TheReverend403** [comment]
The tags are there now, they just aren't linked in the page. I'll figure out a way to do that at some point.

**Comment by neeasade** [comment]
Thanks. I think I saw some javascript solutions(auto add links to h3 elements for example), willing to take a pr if I investigate?

**Comment by TheReverend403** [comment]
If you can get that working, absolutely.

**Comment by TheReverend403** [comment]
Added in 56dc4b71acd057c2586ffa3d7937f797fed0eda7
